name = 'Смауг'
surname = 'Золотой'
address = 'Средиземье, Эребор'
metro_station = 'Александровский сад'
phone = 66666666666
data = '30.10.2022'
period = 'двое суток'
color = 'black'
comment = 'У тебя хорошие манеры для вора и лжеца!'